{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/151216/1-151216155H3.jpg' text='' width='230' height='176'} /uploads/allimg/151216/1-151216155H3.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/151216/1-151216155H6.jpg' text='' width='230' height='176'} /uploads/allimg/151216/1-151216155H6.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/151216/1-151216155H7.jpg' text='' width='230' height='176'} /uploads/allimg/151216/1-151216155H7.jpg {/dede:img}
