{dede:pagestyle maxwidth='800' pagepicnum='12' ddmaxwidth='200' row='3' col='4' value='2'/}
{dede:img ddimg='/uploads/allimg/151216/1-151216155T6.jpg' text='' width='230' height='176'} /uploads/allimg/151216/1-151216155T6.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/151216/1-151216155T9.jpg' text='' width='230' height='176'} /uploads/allimg/151216/1-151216155T9.jpg {/dede:img}
{dede:img ddimg='/uploads/allimg/151216/1-151216155U0.jpg' text='' width='230' height='176'} /uploads/allimg/151216/1-151216155U0.jpg {/dede:img}
