
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:tel itemname="联系方式" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:tel>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:qy itemname="区域" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:qy>

<field:nr itemname="内容" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:nr>
