<?php
$z[0]=Array("channel"," <a href=\"[field:typeurl/]\"  rel='dropmenu3'>[field:typename/]</a> ",207,314);
$z[0][4]['type']="top";
$z[1]=Array("global","",348,374);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",448,470);
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",676,697);
$z[3][4]['name']="cfg_qq";
$z[4]=Array("global","",798,820);
$z[4][4]['name']="cfg_qqa";
$z[5]=Array("global","",921,944);
$z[5][4]['name']="cfg_qqab";
$z[6]=Array("global","",1073,1095);
$z[6][4]['name']="cfg_tel";

?>