<?php
$z[0]=Array("field","",254,283);
$z[0][4]['name']="typename";
$z[1]=Array("global","",284,310);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",351,380);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",420,478);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",686,721);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\r\n        <li><a href=\"[field:typelink/]\"  rel='dropmenu'>[field:typename/]</a></li>\r\n       ",832,1053);
$z[5][4]['type']="top";
$z[5][4]['row']="7";
$z[5][4]['currentstyle']="<li class='home'><a href='~typelink~' ~rel~>~typename~</a></li>";
$z[6]=Array("field","",1208,1237);
$z[6][4]['name']="typename";
$z[7]=Array("field","",1269,1298);
$z[7][4]['name']="position";
$z[8]=Array("field","",4140,4199);
$z[8][4]['name']="typeid";
$z[8][4]['function']="GetTopTypename(@me)";
$z[9]=Array("channel","\r\n          <li><a href='[field:typeurl/]'><span>[field:typename/]</span></a></li>\r\n          ",4275,4533);
$z[9][4]['type']="son";
$z[9][4]['row']="10";
$z[9][4]['currentstyle']="<li class='cur'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[10]=Array("include","",4580,4615);
$z[10][4]['filename']="left.htm";
$z[11]=Array("include","",4660,4697);
$z[11][4]['filename']="footer.htm";

?>